### ISSUE TITLE
Owi symbolic : error message in Trap table undefined element context

### ISSUE THREAD

**Issue by epatrizio** [OCamlPro/owi#107] opened 2024-01-18 17:11 UTC
```wast
(module
  (import "symbolic" "i32_symbol" (func $i32_symbol (result i32)))
  (table $t (ref func)
    (elem $f)
  )
  (type $type (func))
  (func $f)
  (func $start
    (call_indirect
      $t
      (type $type)
      (call $i32_symbol)
    )
  )
  (start $start)
)
```
Here is the console trace after symbolic interpretation of this module :
```console
Model:                                 
(model
  (symbol_0 i32 (i32 0)))
Trap: undefined element
Model:
  (model
    (symbol_0 i32 (i32 -2147483648)))
Reached 1 problems!
```
The console trace should be : ?
```console
Trap: undefined element
Model:
  (model
    (symbol_0 i32 (i32 -2147483648)))
Reached 1 problems!
```

**Comment by filipeom** [comment] 2024-01-18 19:02
What is the issue here? It should not print the module? For me looking at the code of `call_indirect` this seems correct:

https://github.com/OCamlPro/owi/blob/main/src/interpret.ml#L795

```ocaml
      let size = Table.size t in
      let> out_of_bounds =
        Bool.or_ I32.(fun_i < const 0l) @@ I32.(consti size <= fun_i)
      in
      if out_of_bounds then Choice.trap Undefined_element
```

If the function index `fun_i` is 0, we will get `out_of_bounds = true` and we Trap with `Undefined_element`

**Comment by filipeom** [comment] 2024-01-18 19:07
I think either value from the model is correct looking at: https://github.com/OCamlPro/owi/blob/main/src/interpret.ml#L797

I think the issue is because we're print the model here: https://github.com/OCamlPro/owi/blob/main/src/choice_monad.ml#L131

So we get two models for the same problem

**Comment by zapashcanon** [comment] 2024-01-18 23:08
Thanks @filipeom, this should be fixed now. @epatrizio could you retry the test you were writing and confirm ?

**Closed** 2024-01-18 23:08 UTC
